/* eslint-disable @typescript-eslint/naming-convention */

/** @type {import('stylelint').Config['rules']} */
export default {
	'no-descending-specificity': true,
	'declaration-block-no-duplicate-custom-properties': true,
	'declaration-block-no-duplicate-properties': true,
	'font-family-no-duplicate-names': true,
	'keyframe-block-no-duplicate-selectors': true,
	'no-duplicate-at-import-rules': true,
	'no-duplicate-selectors': true,
	'block-no-empty': true,
	'comment-no-empty': true,
	'no-empty-source': true,
	'color-no-invalid-hex': true,
	'function-calc-no-unspaced-operator': true,
	'keyframe-declaration-no-important': true,
	'media-query-no-invalid': true,
	'named-grid-areas-no-invalid': true,
	'no-invalid-double-slash-comments': true,
	'no-invalid-position-at-import-rule': true,
	'string-no-newline': true,
	'no-irregular-whitespace': true,
	'custom-property-no-missing-var-function': true,
	'font-family-no-missing-generic-family-keyword': true,
	'function-linear-gradient-no-nonstandard-direction': true,
	'declaration-block-no-shorthand-property-overrides': true,
	'selector-anb-no-unmatchable': true,
	'annotation-no-unknown': true,
	// 'at-rule-no-unknown': true,
	// 'function-no-unknown': true,
	'media-feature-name-no-unknown': true,
	'media-feature-name-value-no-unknown': true,
	'no-unknown-animations': true,
	'no-unknown-custom-media': true,
	'no-unknown-custom-properties': true,
	'property-no-unknown': true,
	'selector-pseudo-class-no-unknown': true,
	'selector-pseudo-element-no-unknown': true,
	'selector-type-no-unknown': true,
	'unit-no-unknown': true,
	'at-rule-no-vendor-prefix': true,
	// 'font-face': ['font-family', 'font-weight', 'font-style', 'font-display'],
	'color-hex-alpha': 'never',
	'color-named': 'never',
	// 'color-no-hex': true,
	// 'comment-word-disallowed-list': [],
	// 'declaration-property-unit-allowed-list': [],
	// 'declaration-property-unit-disallowed-list': [],
	// 'declaration-property-value-allowed-list': [],
	// 'declaration-property-value-disallowed-list': [],
	// 'function-allowed-list': [],
	// 'function-disallowed-list': [],
	'function-url-no-scheme-relative': true,
	// 'function-url-scheme-allowed-list': [],
	// 'function-url-scheme-disallowed-list': [],
	'length-zero-no-unit': true,
	// 'media-feature-name-allowed-list': [],
	// 'media-feature-name-disallowed-list': [],
	// 'media-feature-name-no-vendor-prefix': [],
	// 'media-feature-name-unit-allowed-list': [],
	// 'media-feature-name-value-allowed-list': [],
	// 'property-allowed-list': [],
	// 'property-disallowed-list': [],
	'property-no-vendor-prefix': true,
	// 'rule-selector-property-disallowed-list': [],
	// 'selector-attribute-name-disallowed-list': [],
	// 'selector-attribute-operator-allowed-list': [],
	// 'selector-attribute-operator-disallowed-list': [],
	// 'selector-combinator-allowed-list': [],
	// 'selector-combinator-disallowed-list': [],
	// 'selector-disallowed-list': [],
	// 'selector-no-vendor-prefix': true,
	// 'selector-pseudo-class-allowed-list': [],
	// 'selector-pseudo-class-disallowed-list': [],
	// 'selector-pseudo-element-allowed-list': [],
	// 'selector-pseudo-element-disallowed-list': [],
	'selector-no-qualifying-type': [
		true,
		{
			ignore: ['attribute', 'class', 'id'],
		},
	],
	'unit-allowed-list': ['px', 'rem', 'vw', 'vh', '%', 'deg', 'ms'],
	// 'unit-disallowed-list': [],
	// 'value-no-vendor-prefix': true,
	// 'function-name-case': 'lower',
	// 'selector-type-case': 'lower',
	// 'value-keyword-case': 'lower',
	// 'at-rule-empty-line-before': 'never',
	// 'comment-empty-line-before': 'never',
	// 'custom-property-empty-line-before': 'never',
	'declaration-empty-line-before': null,
	'rule-empty-line-before': null,
	'declaration-block-single-line-max-declarations': 1,
	// 'declaration-property-max-values': {},
	// 'max-nesting-depth': 5,
	// 'selector-max-attribute': 3,
	// 'selector-max-class': 3,
	// 'selector-max-combinators': 3,
	// 'selector-max-compound-selectors': 5,
	// 'selector-max-id': 2,
	// 'selector-max-pseudo-class: 3,
	// 'selector-max-specificity': '',
	// 'selector-max-type': 3,
	'selector-max-universal': 1,
	'time-min-milliseconds': 100,
	'alpha-value-notation': 'percentage',
	'color-function-notation': 'modern',
	'color-hex-length': 'long',
	'font-weight-notation': 'numeric',
	'hue-degree-notation': 'angle',
	'import-notation': 'string',
	'keyframe-selector-notation': 'percentage',
	'lightness-notation': 'percentage',
	'media-feature-range-notation': 'context',
	'selector-not-notation': 'complex',
	'selector-pseudo-element-colon-notation': 'single',
	// 'comment-pattern': '',
	// 'custom-media-pattern': '',
	// 'custom-property-pattern': '',
	// 'keyframes-name-pattern': '',
	'selector-class-pattern': null,
	// 'selector-id-pattern': '',
	// 'selector-nested-pattern': '',
	'font-family-name-quotes': 'always-unless-keyword',
	'function-url-quotes': 'never',
	'selector-attribute-quotes': 'always',
	'declaration-block-no-redundant-longhand-properties': true,
	'shorthand-property-no-redundant-values': true,
	'comment-whitespace-inside': 'always',
	'function-name-case': null,
	'scss/at-rule-no-unknown': true,
	'scss/at-mixin-pattern': null,
	'scss/at-function-pattern': null,
	'scss/dollar-variable-pattern': null,
	'scss/dollar-variable-empty-line-before': null,
};